### ISSUE TITLE
CNAME warning

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [PetProjectsColab/PetProjectsColab.github.io#1]
I think this is because the name of the repository has camel case whereas the url has all small case.
check this example [out](https://github.com/deshmukhrajvardhan/deshmukhrajvardhan.github.io)

**Comment by ISHITADG** [comment]
Issue resolved. I simply removed the CNAME file and it worked.

**Comment by deshmukhrajvardhan** [comment]
i don't remember why we had that in the first place :p .(Maybe for having extra alias name that would point to a custom domain). glad its resloved
